language: node_js
node_js:
- '8'
services:
cache:
  directories:
    - node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch: master
    bucket: $AWS_S3_BUCKET
    region: us-east-1
    acl: public_read

script:
  - npm run build
  - mkdir -p dpl_cd_upload
  - mv ./build/* dpl_cd_upload

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  on:
    branch: master