language: node_js
node_js:
- '8'
services:
cache:
  directories:
    - node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: andy-shi88/testing-travis
    bucket: for-travis-deployment-only
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: for-travis-deployment-only
    key: latest.zip
    bundle_type: zip
    application: CodeDeployGitHubDemo-AppPower
    deployment_group: CodeDeployGitHubDemo-DepGrpPower

    region: us-east-1
    on: *2
    wait-until-deployed: true

after_deploy:
  - ./restart.sh

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip