language: node_js
node_js:
- '8'
services:
cache:
  directories:
    - node_modules
deploy:
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: AKIAIUI22CAR6L6JCV7Q
    secret_access_key: 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
    application: product-app-client
    deployment_group: travis-deployment-test
    region: us-east-1
    on:
      branch: master
    wait-until-deployed: true

after_deploy:
  - ./restart.sh

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip