language: node_js
node_js:
- '8'
services:
cache:
  directories:
    - node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch: master
    bucket: for-travis-deployment-only
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: for-travis-deployment-only
    key: latest.zip
    bundle_type: zip
    application: CodeDeployGitHubDemo-AppPower
    deployment_group: CodeDeployGitHubDemo-DepGrpPower
    region: us-east-1
    on:
      branch: master
    wait-until-deployed: true

script:
  - zip -qr latest ./*
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip