version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ubuntu/travis/testing-travis
    overwrite: true

hooks:
  BeforeInstall:
    - location: ./script/backup.sh
      runas: root
  AfterInstall:
    - location: ./script/npm-install.sh
      runas: root
  ApplicationStart:
    - location: ./script/npm-start.sh
      runas: root
