version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ubuntu/travis/testing-travis
    overwrite: true

hooks:
  ApplicationStop:
    - location: ./script/application-stop.sh
  BeforeInstall:
    - location: ./script/backup.sh
  ApplicationStart:
    - location: ./script/npm-start.sh
